### ISSUE TITLE
Аргумент Exception со значением по умолчанию

### ISSUE THREAD

**Issue by mbaturin-rubbi** [Xom94o4ek/SubsidyCalculation#1]
https://github.com/Xom94o4ek/SubsidyCalculation/blob/6d6540bfadc4d8775736f0e9ba9cc7147f7695f9/SubsidyCalculation/SubsidyCalculation.cs#L56

Создай аргумент Exception ex = null
В коде напиши if(ex == null) { ex = new Exception .......... }

Так ты можешь схлопнуть между собой два метода с одиннаковым содержимым

**Comment by Xom94o4ek** [comment]
Выполнено
